---
abstract: 'roles that can be commonly used, for the mutual benefit of all'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.142690'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Role-Commons
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Object::AUTHORITY:
    file: lib/Object/AUTHORITY.pm
    version: '0.103'
  Role::Commons:
    file: lib/Role/Commons.pm
    version: '0.103'
  Role::Commons::Authority:
    file: lib/Role/Commons/Authority.pm
    version: '0.103'
  Role::Commons::ObjectID:
    file: lib/Role/Commons/ObjectID.pm
    version: '0.103'
  Role::Commons::Tap:
    file: lib/Role/Commons/Tap.pm
    version: '0.103'
requires:
  Module::Runtime: '0'
  Moo::Role: '0'
  Object::ID: '0'
  Types::Standard: '1.000000'
  match::simple: '0'
  perl: '5.008'
resources:
  Identifier: http://purl.org/NET/cpan-uri/dist/Role-Commons/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Role-Commons
  homepage: https://metacpan.org/release/Role-Commons
  license: http://dev.perl.org/licenses/
version: '0.103'
