---
abstract: 'roles that can be commonly used, for the mutual benefit of all'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::7 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Role-Commons
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Object::AUTHORITY:
    file: lib/Object/AUTHORITY.pm
    version: '0.102'
  Object::Tap:
    file: lib/Object/Tap.pm
    version: '0.102'
  Role::Commons:
    file: lib/Role/Commons.pm
    version: '0.102'
  Role::Commons::Authority:
    file: lib/Role/Commons/Authority.pm
    version: '0.102'
  Role::Commons::ObjectID:
    file: lib/Role/Commons/ObjectID.pm
    version: '0.102'
  Role::Commons::Tap:
    file: lib/Role/Commons/Tap.pm
    version: '0.102'
  authority::shared:
    file: lib/authority/shared.pm
    version: '0.102'
requires:
  Class::Load: '0'
  Moo::Role: '0'
  Object::ID: '0'
  Scalar::Does: '0.006'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Role-Commons/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Role-Commons
  homepage: https://metacpan.org/release/Role-Commons
  license: http://dev.perl.org/licenses/
version: '0.102'
